### ISSUE TITLE
License is not packaged

### ISSUE THREAD

**Issue by spoenemann** [kuniss/epsilon-ide-extensions#3]
Hi @kuniss! The epsilon-eag-dark-theme and epsilon-eag-light-theme are missing a license. Could you republish those extensions and ensure to package the LICENSE file? I would also suggest to add an entry `"license": "EPL-2.0"` to the package.json of every extension.

**Comment by kuniss** [comment]
License files packaged, license specification corrected. See OpenVSX entries where license link opens the according license file.

**Comment by spoenemann** [comment]
Great! We'll have to delete the older versions because of the missing license.

**Comment by kuniss** [comment]
Please wait some days . I need to incorporate the new versions first into a dependent gitpod utilizing project.

**Comment by kuniss** [comment]
@spoenemann , now they can be deleted!
